### ISSUE TITLE
TypeError: component.values.forEach

### ISSUE THREAD

**Issue by tithvannarith** [formio/angular-formio#173]
I got this error while i working with angular 6.0.3 : 
An error occured within custom function for unknown TypeError: component.values.forEach is not a function
    at builder.js:93
    at utils.js:251
    at Array.forEach (<anonymous>)
    at eachComponent (utils.js:233)
    at utils.js:275
    at Array.forEach (<anonymous>)
    at eachComponent (utils.js:233)
    at utils.js:275
    at Array.forEach (<anonymous>)
    at eachComponent (utils.js:233)

**Comment by travist** [comment]
This would have been a bug with the core renderer. I have made many updates to that which included in the latest 2.0.0-alpha.8 release.
